-- 030_perf_indexes.sql — NO-OP
--
-- Bu migration boş bırakılmıştır.
-- 001_initial_schema.sql (302-308) içinde aynı kolonlar için index'ler zaten mevcuttur:
--   idx_sales_orders_customer   → sales_orders(customer_id)
--   idx_sales_orders_commercial → sales_orders(commercial_status)
--   idx_order_lines_order       → order_lines(order_id)
--   idx_order_lines_product     → order_lines(product_id)
-- Yeni isimle CREATE INDEX IF NOT EXISTS, isim bazlı kontrol ettiğinden
-- aynı kolona duplicate index yaratırdı. Migration numarası korunmuştur.
